#
# Cookbook Name:: rvm
# Recipe:: default
#
# Copyright 2012, Joseph Fredette
#
# All rights reserved - Do Not Redistribute
#

%w(gcc patch curl zlib readline libxml2 libxslt git autoconf automake diffutils make libtool bison subversion).each do |pkg|
  package pkg do
    action :install
  end
end

# create a sudoer user to perform the install from
user 'rvm' do
  action :create
  shell '/bin/bash'
  gid 'adm'
end

# THIS MUST GO FIRST (well... second)
# -- if it doesn't, then we'll install and then immediately upgrade
#
#only when rvm is installed already
bash 'upgrade rvm to most recent stable version' do
  user 'rvm'
  code 'rvm get stable'
  only_if 'test -e /user/local/rvm/bin/rvm'
end

# THIS MUST GO SECOND
# -- see above
#
#only if rvm isn't installed
bash 'Multi-user rvm install' do
  user 'rvm'
  code 'curl -L https://get.rvm.io | sudo bash ; echo'
end

# clear out the /etc/gemrc generated by pacman -- we don't need it
# everything should go through rvm.
file '/etc/gemrc' do
  action [:delete, :touch]
  backup false
end

cookbook_file '/etc/rvmrc' do
  action :create
  backup false

  group 'rvm'
  owner 'rvm'
  mode '755'

  source 'rvmrc'
end

bash 'load rvm scripts at root login' do
  user 'root'
  code 'echo "source /etc/profile.d/rvm.sh" > ~/.bashrc'
end

group 'rvm' do
  #we're just asserting it gets created correctly, this will raise
  #an exception if it isn't.
  action :modify
end

# install a recent version of ruby so rvm will have a default to rely on 
# for bootstrapping other rubies.
rvm_ruby '1.9.3' do
  options ['--default']
end


